steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/devsecops-3-tier-463414/myapps-repository/myapp1:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/devsecops-3-tier-463414/myapps-repository/myapp1:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

